[package]
name = "preferential-graphs"
version = "0.1.0"
authors = ["Marcelo Miranda <marcelo.caridade@protonmail.com>"]

[dependencies]
petgraph = "0.4.11"
rand = "0.4.2"
clap = "2.31"
criterion-plot = "0.2"
